#!/usr/bin/env bash
set -euo pipefail
shopt -s extglob

VERBOSE=0

for opt in "$@"; do
  case $opt in
    -+(v))
      VERBOSE="$((${#opt} - 1))"
      shift
      ;;
    !(-*))
      break
      ;;
  esac
done

. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/lib/paths.sh
. "${LIB_PATH}/common.sh"
. "${LIB_PATH}/commands.sh"

COMMAND="${1:-help}"
shift
if available_command? "${COMMAND}" ; then
  "command.${COMMAND}" "$@"
else
  cat <<-EOF
Unknown command: ${COMMAND}

Available commands
$(
  for c in "${AVAILABLE_COMMANDS[@]}"; do
    echo -e "  ${c}"
  done
)
EOF
  exit 100
fi
